---
title: "Standarisasi"
author: "KSM - 3"
date: "11/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Standarisasi adalah menstandarkan kumpulan data yang besar yang memiliki banyak kolom dengan rentang dan unit yang bervariasi.\
Terdapat 3 methode untuk melakukan standarisasi :

```{r}
# Method 1 : Using scale function
# Creating Dataset
X <- c('A','B','C','D','E','F')
Y <- c(15,16,20,19,19,17)
Z <- c(5.0,4.0,5.0,2.0,1.0,3.0)

dataframe <- data.frame(Name = X, Age = Y, CGPA = Z )
dataframe

# applying scale function
dataframe[2 : 3] <- as.data.frame(scale(dataframe[2 : 3]))

# displaying result
dataframe

```

```{r}

# Method 2 : Using base R
# Creating Dataset
X <- c('A', 'B', 'C', 'D', 'E', 'F')
Y <- c(15, 16, 20, 19, 19, 17)
Z <- c(5.0, 4.0, 5.0, 2.0, 1.0, 3.0)

dataframe1 <- data.frame(Name = X, Age = Y, CGPA = Z )
dataframe1

# creating Standardization function
standardize = function(x){
  z <- (x - mean(x)) / sd(x)
  return( z)
}

# apply your function to the dataset
dataframe1[2:3] <-
  apply(dataframe1[2:3], 2, standardize)

#displaying result
dataframe1
```

```{r}
# Method 3 : Using Package Dplyr
library(dplyr)

#make this example reproducible 
set.seed(1)

#create original data frame
df <- data.frame(var1= runif(10, 0, 50), 
                 var2= runif(10, 2, 23),
                 var3= runif(10, 5, 38))

#view original data frame 
df

#scale var1 to have mean = 0 and standard deviation = 1
df2 <- df %>% 
  mutate_at(c('var1'), ~(scale(.) %>% 
                           as.vector))
df2

```